### ISSUE TITLE
Cannot find name 'Request' - When compiling to typescript

### ISSUE THREAD

**Issue by BasarN** [aerogear/keycloak-connect-graphql#112] opened 2020-11-12 15:40 UTC
Hi, I'm currently using 
```
"typescript": "^4.0.3",
"express": "^4.17.1",
"keycloak-connect": "^11.0.2",
"keycloak-connect-graphql": "^0.6.3",
```
When compiling with tsc I get Error:
```
node_modules/keycloak-connect-graphql/dist/KeycloakContext.d.ts:4:41 - error TS2304: Cannot find name 'Request'.

4 export interface GrantedRequest extends Request {

```

**Comment by wtrocki** [comment] 2020-11-12 16:11
Duplicate of: https://github.com/aerogear/keycloak-connect-graphql/issues/70

**Closed by wtrocki** 2020-11-12 16:11 UTC
